### ISSUE TITLE
Error running the prompt on 2 Nvidia GPU - A100

### ISSUE THREAD

**Issue by bhanuc** [MiuGod0126/ppllama#2]
Hi there, I am getting error - 
Command -  python -m paddle.distributed.launch  scripts/example_cpu.py --prompt "The capital of Germany is the city of" --mp 1 --ckpt_dir ../65B/ --tokenizer_path  ../tokenizer.model
```Error: Can not import paddle core while this file exists: /root/anaconda3/envs/ENVNAME2/lib/python3.10/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "/root/anaconda3/envs/ENVNAME2/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/root/anaconda3/envs/ENVNAME2/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/root/anaconda3/envs/ENVNAME2/lib/python3.10/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/root/anaconda3/envs/ENVNAME2/lib/python3.10/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/root/anaconda3/envs/ENVNAME2/lib/python3.10/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/root/anaconda3/envs/ENVNAME2/lib/python3.10/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/root/anaconda3/envs/ENVNAME2/lib/python3.10/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/root/anaconda3/envs/ENVNAME2/lib/python3.10/site-packages/paddle/fluid/core.py", line 338, in <module>
    raise e
  File "/root/anaconda3/envs/ENVNAME2/lib/python3.10/site-packages/paddle/fluid/core.py", line 274, in <module>
    from . import libpaddle
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory```
My system CUDA is 11.6, this seems like a cuda mismatch error, though I am not able to pinpoint how to fix this

**Comment by jiaohuix** [comment]
hi, try installing paddle with this command: 
`conda install paddlepaddle-gpu==2.4.2 cudatoolkit=11.6 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
-c conda-forge`
For more information please see the paddle website： [paddle](https://www.paddlepaddle.org.cn/en/install/quick?docurl=/documentation/docs/en/install/pip/linux-pip_en.html)
